package ekkel.gameboy.cpu.sharpLR35902.decoders;

import core.cpu.CPU;
import core.cpu.Standard8BitDSL;
import core.cpu.opcodes.Decoder;
import core.cpu.opcodes.OpcodeFactory;
import core.mmu.MMU;
import ekkel.gameboy.cpu.opcodes.adc.ADC_A_B;
import ekkel.gameboy.cpu.opcodes.adc.ADC_A_C;
import ekkel.gameboy.cpu.opcodes.adc.ADC_A_d8;
import ekkel.gameboy.cpu.opcodes.add.*;
import ekkel.gameboy.cpu.opcodes.and.AND_A;
import ekkel.gameboy.cpu.opcodes.and.AND_C;
import ekkel.gameboy.cpu.opcodes.and.AND_d8;
import ekkel.gameboy.cpu.opcodes.branch.*;
import ekkel.gameboy.cpu.opcodes.call.CALL_NC_a16;
import ekkel.gameboy.cpu.opcodes.call.CALL_NZ_d16;
import ekkel.gameboy.cpu.opcodes.call.CALL_Z_a16;
import ekkel.gameboy.cpu.opcodes.call.CALL_a16;
import ekkel.gameboy.cpu.opcodes.cp.*;
import ekkel.gameboy.cpu.opcodes.dec.*;
import ekkel.gameboy.cpu.opcodes.inc.*;
import ekkel.gameboy.cpu.opcodes.ld.*;
import ekkel.gameboy.cpu.opcodes.ldd.LDD_HL_A;
import ekkel.gameboy.cpu.opcodes.ldh.LDH_A_a8;
import ekkel.gameboy.cpu.opcodes.ldh.LDH_a8_A;
import ekkel.gameboy.cpu.opcodes.ldi.LDI_A_HL;
import ekkel.gameboy.cpu.opcodes.ldi.LDI_HL_A;
import ekkel.gameboy.cpu.opcodes.misc.*;
import ekkel.gameboy.cpu.opcodes.or.*;
import ekkel.gameboy.cpu.opcodes.push.PUSH_AF;
import ekkel.gameboy.cpu.opcodes.push.PUSH_BC;
import ekkel.gameboy.cpu.opcodes.push.PUSH_DE;
import ekkel.gameboy.cpu.opcodes.push.PUSH_HL;
import ekkel.gameboy.cpu.opcodes.ret.*;
import ekkel.gameboy.cpu.opcodes.rst.RST_38H;
import ekkel.gameboy.cpu.opcodes.sub.SUB_A_d8;
import ekkel.gameboy.cpu.opcodes.sub.SUB_C;
import ekkel.gameboy.cpu.opcodes.xor.*;
import ekkel.gameboy.cpu.opcodes.pop.POP_AF;
import ekkel.gameboy.cpu.opcodes.pop.POP_BC;
import ekkel.gameboy.cpu.opcodes.pop.POP_DE;
import ekkel.gameboy.cpu.opcodes.pop.POP_HL;

public class StandardDecoder  extends Decoder {
    public StandardDecoder(CPU cpu, MMU mmuImpl) {
        super(cpu);
        this.opcodeDSL = new Standard8BitDSL(mmuImpl, cpu);
        OpcodeFactory opcodeFactory = new OpcodeFactory(this.opcodeDSL, mmuImpl,cpu);   this.addOpcode(opcodeFactory.newOpcode(NOP.class));
        this.addOpcode(opcodeFactory.newOpcode(CB.class));
        this.addOpcode(opcodeFactory.newOpcode(JP_a16.class));
        this.addOpcode(opcodeFactory.newOpcode(JP_HL.class));
        this.addOpcode(opcodeFactory.newOpcode(JR_r8.class));


        this.addOpcode(opcodeFactory.newOpcode(DI.class));
        this.addOpcode(opcodeFactory.newOpcode(LD_SP_d16.class));
        this.addOpcode(opcodeFactory.newOpcode(LD_DE_d16.class));
        this.addOpcode(opcodeFactory.newOpcode(LD_BC_d16.class));

        this.addOpcode(opcodeFactory.newOpcode(LD_a16_A.class));

        this.addOpcode(opcodeFactory.newOpcode(LD_A_DE.class));
        this.addOpcode(opcodeFactory.newOpcode(LD_B_HL.class));
        this.addOpcode(opcodeFactory.newOpcode(LD_C_HL.class));
        this.addOpcode(opcodeFactory.newOpcode(LD_D_HL.class));
        this.addOpcode(opcodeFactory.newOpcode(LD_L_HL.class));
        this.addOpcode(opcodeFactory.newOpcode(LD_A_HL.class));
        this.addOpcode(opcodeFactory.newOpcode(LD_A_d8.class));
        this.addOpcode(opcodeFactory.newOpcode(LD_B_d8.class));
        this.addOpcode(opcodeFactory.newOpcode(LD_C_d8.class));
        this.addOpcode(opcodeFactory.newOpcode(LD_D_d8.class));
        this.addOpcode(opcodeFactory.newOpcode(LD_E_d8.class));
        this.addOpcode(opcodeFactory.newOpcode(LD_L_d8.class));
        this.addOpcode(opcodeFactory.newOpcode(LD_H_d8.class));
        this.addOpcode(opcodeFactory.newOpcode(LDH_a8_A.class));
        this.addOpcode(opcodeFactory.newOpcode(LDH_A_a8.class));
        this.addOpcode(opcodeFactory.newOpcode(LD_HL_d16.class));
        this.addOpcode(opcodeFactory.newOpcode(LD_DE_A.class));
        this.addOpcode(opcodeFactory.newOpcode(CALL_a16.class));
        this.addOpcode(opcodeFactory.newOpcode(CALL_NZ_d16.class));
        this.addOpcode(opcodeFactory.newOpcode(CALL_NC_a16.class));
        this.addOpcode(opcodeFactory.newOpcode(CALL_Z_a16.class));
        this.addOpcode(opcodeFactory.newOpcode(LD_Ci_A.class));
        this.addOpcode(opcodeFactory.newOpcode(LD_A_L.class));
        this.addOpcode(opcodeFactory.newOpcode(LD_A_H.class));
        this.addOpcode(opcodeFactory.newOpcode(LD_H_A.class));
        this.addOpcode(opcodeFactory.newOpcode(LD_A_B.class));
        this.addOpcode(opcodeFactory.newOpcode(LD_B_A.class));
        this.addOpcode(opcodeFactory.newOpcode(LD_B_H.class));
        this.addOpcode(opcodeFactory.newOpcode(LD_D_D.class));
        this.addOpcode(opcodeFactory.newOpcode(LD_D_A.class));
        this.addOpcode(opcodeFactory.newOpcode(LD_D_B.class));
        this.addOpcode(opcodeFactory.newOpcode(LD_D_C.class));
        this.addOpcode(opcodeFactory.newOpcode(LD_D_E.class));
        this.addOpcode(opcodeFactory.newOpcode(LD_E_L.class));
        this.addOpcode(opcodeFactory.newOpcode(LD_C_A.class));
        this.addOpcode(opcodeFactory.newOpcode(LD_C_B.class));
        this.addOpcode(opcodeFactory.newOpcode(LD_A_A.class));
        this.addOpcode(opcodeFactory.newOpcode(LD_L_A.class));
        this.addOpcode(opcodeFactory.newOpcode(LD_A_C.class));
        this.addOpcode(opcodeFactory.newOpcode(LD_A_D.class));
        this.addOpcode(opcodeFactory.newOpcode(LD_D_H.class));
        this.addOpcode(opcodeFactory.newOpcode(LD_A_E.class));
        this.addOpcode(opcodeFactory.newOpcode(LD_B_B.class));
        this.addOpcode(opcodeFactory.newOpcode(LD_B_C.class));
        this.addOpcode(opcodeFactory.newOpcode(LD_B_L.class));
        this.addOpcode(opcodeFactory.newOpcode(LD_C_D.class));
        this.addOpcode(opcodeFactory.newOpcode(LD_C_E.class));
        this.addOpcode(opcodeFactory.newOpcode(LD_E_C.class));
        this.addOpcode(opcodeFactory.newOpcode(LD_C_C.class));
        this.addOpcode(opcodeFactory.newOpcode(LD_B_D.class));
        this.addOpcode(opcodeFactory.newOpcode(LD_B_E.class));
        this.addOpcode(opcodeFactory.newOpcode(LD_E_B.class));
        this.addOpcode(opcodeFactory.newOpcode(LD_E_D.class));
        this.addOpcode(opcodeFactory.newOpcode(LD_E_E.class));
        this.addOpcode(opcodeFactory.newOpcode(LD_E_H.class));
        this.addOpcode(opcodeFactory.newOpcode(LD_H_B.class));
        this.addOpcode(opcodeFactory.newOpcode(LD_H_C.class));
        this.addOpcode(opcodeFactory.newOpcode(LD_C_H.class));
        this.addOpcode(opcodeFactory.newOpcode(LD_H_D.class));
        this.addOpcode(opcodeFactory.newOpcode(LD_H_E.class));
        this.addOpcode(opcodeFactory.newOpcode(LD_H_H.class));
        this.addOpcode(opcodeFactory.newOpcode(LD_H_L.class));
        this.addOpcode(opcodeFactory.newOpcode(LD_L_B.class));
        this.addOpcode(opcodeFactory.newOpcode(LD_L_C.class));
        this.addOpcode(opcodeFactory.newOpcode(LD_C_L.class));
        this.addOpcode(opcodeFactory.newOpcode(LD_L_D.class));
        this.addOpcode(opcodeFactory.newOpcode(LD_D_L.class));
        this.addOpcode(opcodeFactory.newOpcode(LD_L_E.class));
        this.addOpcode(opcodeFactory.newOpcode(LD_L_H.class));
        this.addOpcode(opcodeFactory.newOpcode(LD_L_L.class));
        this.addOpcode(opcodeFactory.newOpcode(LD_H_H.class));
        this.addOpcode(opcodeFactory.newOpcode(LD_A_C.class));
        this.addOpcode(opcodeFactory.newOpcode(LD_E_A.class));
        this.addOpcode(opcodeFactory.newOpcode(LD_A_a16.class));
        this.addOpcode(opcodeFactory.newOpcode(LD_HL_A.class));
        this.addOpcode(opcodeFactory.newOpcode(LD_HL_B.class));
        this.addOpcode(opcodeFactory.newOpcode(LD_HL_C.class));
        this.addOpcode(opcodeFactory.newOpcode(LD_HL_D.class));
        this.addOpcode(opcodeFactory.newOpcode(LD_HL_E.class));
        this.addOpcode(opcodeFactory.newOpcode(LD_HL_L.class));
        this.addOpcode(opcodeFactory.newOpcode(LD_HL_H.class));
        this.addOpcode(opcodeFactory.newOpcode(LD_E_HL.class));
        this.addOpcode(opcodeFactory.newOpcode(LD_H_HL.class));
        this.addOpcode(opcodeFactory.newOpcode(LD_A_BC.class));

        this.addOpcode(opcodeFactory.newOpcode(LD_a16_SP.class));
        this.addOpcode(opcodeFactory.newOpcode(LD_HL_SP_add_r8.class));
        this.addOpcode(opcodeFactory.newOpcode(LD_HL_d8.class));
        this.addOpcode(opcodeFactory.newOpcode(LD_SP_HL.class));
        this.addOpcode(opcodeFactory.newOpcode(CP_d8.class));
        this.addOpcode(opcodeFactory.newOpcode(CP_B.class));
        this.addOpcode(opcodeFactory.newOpcode(CP_C.class));
        this.addOpcode(opcodeFactory.newOpcode(CP_D.class));
        this.addOpcode(opcodeFactory.newOpcode(CP_E.class));

        this.addOpcode(opcodeFactory.newOpcode(RET.class));
        this.addOpcode(opcodeFactory.newOpcode(RET_NC.class));
        this.addOpcode(opcodeFactory.newOpcode(RET_NZ.class));
        this.addOpcode(opcodeFactory.newOpcode(RET_C.class));
        this.addOpcode(opcodeFactory.newOpcode(RET_Z.class));

        this.addOpcode(opcodeFactory.newOpcode(PUSH_HL.class));
        this.addOpcode(opcodeFactory.newOpcode(PUSH_BC.class));
        this.addOpcode(opcodeFactory.newOpcode(PUSH_DE.class));
        this.addOpcode(opcodeFactory.newOpcode(PUSH_AF.class));

        this.addOpcode(opcodeFactory.newOpcode(POP_AF.class));
        this.addOpcode(opcodeFactory.newOpcode(POP_BC.class));
        this.addOpcode(opcodeFactory.newOpcode(POP_DE.class));
        this.addOpcode(opcodeFactory.newOpcode(POP_HL.class));

        this.addOpcode(opcodeFactory.newOpcode(INC_HL.class));
        this.addOpcode(opcodeFactory.newOpcode(INC_BC.class));
        this.addOpcode(opcodeFactory.newOpcode(INC_DE.class));
        this.addOpcode(opcodeFactory.newOpcode(INC_SP.class));
        this.addOpcode(opcodeFactory.newOpcode(INC_A.class));
        this.addOpcode(opcodeFactory.newOpcode(INC_B.class));
        this.addOpcode(opcodeFactory.newOpcode(INC_C.class));
        this.addOpcode(opcodeFactory.newOpcode(INC_D.class));
        this.addOpcode(opcodeFactory.newOpcode(INC_E.class));
        this.addOpcode(opcodeFactory.newOpcode(INC_L.class));
        this.addOpcode(opcodeFactory.newOpcode(INC_H.class));
        this.addOpcode(opcodeFactory.newOpcode(LDI_A_HL.class));
        this.addOpcode(opcodeFactory.newOpcode(LDI_HL_A.class));
        this.addOpcode(opcodeFactory.newOpcode(LDD_HL_A.class));
        this.addOpcode(opcodeFactory.newOpcode(OR_d8.class));
        this.addOpcode(opcodeFactory.newOpcode(OR_A.class));
        this.addOpcode(opcodeFactory.newOpcode(OR_B.class));
        this.addOpcode(opcodeFactory.newOpcode(OR_C.class));
        this.addOpcode(opcodeFactory.newOpcode(OR_D.class));
        this.addOpcode(opcodeFactory.newOpcode(OR_E.class));
        this.addOpcode(opcodeFactory.newOpcode(OR_H.class));
        this.addOpcode(opcodeFactory.newOpcode(OR_L.class));
        this.addOpcode(opcodeFactory.newOpcode(OR_HL.class));
        this.addOpcode(opcodeFactory.newOpcode(AND_d8.class));
        this.addOpcode(opcodeFactory.newOpcode(AND_A.class));
        this.addOpcode(opcodeFactory.newOpcode(AND_C.class));
        this.addOpcode(opcodeFactory.newOpcode(JR_Z_r8.class));
        this.addOpcode(opcodeFactory.newOpcode(JR_NZ_r8.class));

        this.addOpcode(opcodeFactory.newOpcode(JR_NC_r8.class));
        this.addOpcode(opcodeFactory.newOpcode(JR_C_r8.class));
        this.addOpcode(opcodeFactory.newOpcode(DEC_A.class));
        this.addOpcode(opcodeFactory.newOpcode(DEC_B.class));
        this.addOpcode(opcodeFactory.newOpcode(DEC_C.class));
        this.addOpcode(opcodeFactory.newOpcode(DEC_E.class));
        this.addOpcode(opcodeFactory.newOpcode(DEC_L.class));
        this.addOpcode(opcodeFactory.newOpcode(DEC_H.class));
        this.addOpcode(opcodeFactory.newOpcode(DEC_BC.class));
        this.addOpcode(opcodeFactory.newOpcode(DEC_DE.class));
        this.addOpcode(opcodeFactory.newOpcode(DEC_iHL.class));
        this.addOpcode(opcodeFactory.newOpcode(DEC_SP.class));
        this.addOpcode(opcodeFactory.newOpcode(SUB_A_d8.class));
        this.addOpcode(opcodeFactory.newOpcode(SUB_C.class));
        this.addOpcode(opcodeFactory.newOpcode(XOR_A.class));
        this.addOpcode(opcodeFactory.newOpcode(XOR_C.class));
        this.addOpcode(opcodeFactory.newOpcode(XOR_L.class));
        this.addOpcode(opcodeFactory.newOpcode(XOR_HL.class));
        this.addOpcode(opcodeFactory.newOpcode(XOR_d8.class));
        this.addOpcode(opcodeFactory.newOpcode(ADD_A_d8.class));
        this.addOpcode(opcodeFactory.newOpcode(ADD_A_E.class));
        this.addOpcode(opcodeFactory.newOpcode(ADD_A_C.class));
        //this.addOpcode(opcodeFactory.newOpcode(ADD_A_B.class));
        this.addOpcode(opcodeFactory.newOpcode(ADD_HL_HL.class));
        this.addOpcode(opcodeFactory.newOpcode(ADD_HL_DE.class));
        this.addOpcode(opcodeFactory.newOpcode(ADD_HL_SP.class));
        this.addOpcode(opcodeFactory.newOpcode(ADD_SP_r8.class));
        this.addOpcode(opcodeFactory.newOpcode(ADC_A_d8.class));
        this.addOpcode(opcodeFactory.newOpcode(ADC_A_B.class));
        this.addOpcode(opcodeFactory.newOpcode(ADC_A_C.class));
        this.addOpcode(opcodeFactory.newOpcode(RRA.class));
        this.addOpcode(opcodeFactory.newOpcode(RLCA.class));
        this.addOpcode(opcodeFactory.newOpcode(STOP.class));
        this.addOpcode(opcodeFactory.newOpcode(SCF.class));
        this.addOpcode(opcodeFactory.newOpcode(CPL.class));
        this.addOpcode(opcodeFactory.newOpcode(RST_38H.class));

        this.addOpcode(opcodeFactory.newOpcode(SBC_A_d8.class));
    }
}
